name: XServerSync
version: '1.0-SNAPSHOT'
main: dev.qelli.minecraft.xserversync.XServerSync
api-version: '1.13'
softdepend: [ TAB, PlaceholderAPI ]
depend: [ ProtocolLib ]
authors: [ blithe_kitsune ]
website: https://qelli.dev
commands:
  xserversync:
    description: XServerSync Admin suite
    usage: /xserversync
    permission: xserversync.admin
    aliases: [ xss, xsync ]